// bible-data.js - 创世记 第1-10章 完整数据
window.BIBLE_DATA = {
  "gen": {
    "chapters": {
      "1": {
        "1": {"zh": "起初，神创造天地。", "en": "In the beginning God created the heavens and the earth."},
        "2": {"zh": "地是空虚混沌，渊面黑暗；神的灵运行在水面上。", "en": "And the earth was waste and void; and darkness was upon the face of the deep: and the Spirit of God moved upon the face of the waters."},
        "3": {"zh": "神说：要有光，就有了光。", "en": "And God said, Let there be light: and there was light."},
        "4": {"zh": "神看光是好的，就把光暗分开了。", "en": "And God saw the light, that it was good: and God divided the light from the darkness."},
        "5": {"zh": "神称光为昼，称暗为夜。有晚上，有早晨，这是头一日。", "en": "And God called the light Day, and the darkness he called Night. And there was evening and there was morning, one day."},
        "6": {"zh": "神说：诸水之间要有空气，将水分为上下。", "en": "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters."},
        "7": {"zh": "神就造出空气，将空气以下的水、空气以上的水分开了。事就这样成了。", "en": "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so."},
        "8": {"zh": "神称空气为天。有晚上，有早晨，是第二日。", "en": "And God called the firmament Heaven. And there was evening and there was morning, a second day."},
        "9": {"zh": "神说：天下的水要聚在一处，使旱地露出来。事就这样成了。", "en": "And God said, Let the waters under the heavens be gathered together unto one place, and let the dry land appear: and it was so."},
        "10": {"zh": "神称旱地为地，称水的聚处为海。神看着是好的。", "en": "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good."},
        "11": {"zh": "神说：地要发生青草和结种子的菜蔬，并结果子的树木，各从其类，果子都包着核。事就这样成了。", "en": "And God said, Let the earth put forth grass, herbs yielding seed, and fruit-trees bearing fruit after their kind, wherein is the seed thereof, upon the earth: and it was so."},
        "12": {"zh": "于是地发生了青草和结种子的菜蔬，各从其类；并结果子的树木，各从其类；果子都包着核。神看着是好的。", "en": "And the earth brought forth grass, herbs yielding seed after their kind, and trees bearing fruit, wherein is the seed thereof, after their kind: and God saw that it was good."},
        "13": {"zh": "有晚上，有早晨，是第三日。", "en": "And there was evening and there was morning, a third day."},
        "14": {"zh": "神说：天上要有光体，可以分昼夜，作记号，定节令、日子、年岁，", "en": "And God said, Let there be lights in the firmament of heaven to divide the day from the night; and let them be for signs, and for seasons, and for days and years:"},
        "15": {"zh": "并要发光在天空，普照在地上。事就这样成了。", "en": "and let them be for lights in the firmament of heaven to give light upon the earth: and it was so."},
        "16": {"zh": "于是神造了两个大光，大的管昼，小的管夜，又造众星，", "en": "And God made the two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also."},
        "17": {"zh": "就把这些光摆列在天空，普照在地上，", "en": "And God set them in the firmament of heaven to give light upon the earth,"},
        "18": {"zh": "管理昼夜，分别明暗。神看着是好的。", "en": "and to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good."},
        "19": {"zh": "有晚上，有早晨，是第四日。", "en": "And there was evening and there was morning, a fourth day."},
        "20": {"zh": "神说：水要多多滋生有生命的物；要有雀鸟飞在地面以上，天空之中。", "en": "And God said, Let the waters swarm with swarms of living creatures, and let birds fly above the earth in the open firmament of heaven."},
        "21": {"zh": "神就造出大鱼和水中所滋生各样有生命的动物，各从其类；又造出各样飞鸟，各从其类。神看着是好的。", "en": "And God created the great sea-monsters, and every living creature that moveth, wherewith the waters swarmed, after their kind, and every winged bird after its kind: and God saw that it was good."},
        "22": {"zh": "神就赐福给这一切，说：滋生繁多，充满海中的水；雀鸟也要多生在地上。", "en": "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth."},
        "23": {"zh": "有晚上，有早晨，是第五日。", "en": "And there was evening and there was morning, a fifth day."},
        "24": {"zh": "神说：地要生出活物来，各从其类；牲畜、昆虫、野兽，各从其类。事就这样成了。", "en": "And God said, Let the earth bring forth living creatures after their kind, cattle, and creeping things, and beasts of the earth after their kind: and it was so."},
        "25": {"zh": "于是神造出野兽，各从其类；牲畜，各从其类；地上一切昆虫，各从其类。神看着是好的。", "en": "And God made the beasts of the earth after their kind, and the cattle after their kind, and everything that creepeth upon the ground after its kind: and God saw that it was good."},
        "26": {"zh": "神说：我们要照着我们的形像、按着我们的样式造人，使他们管理海里的鱼、空中的鸟、地上的牲畜，和全地，并地上所爬的一切昆虫。", "en": "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the heavens, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth."},
        "27": {"zh": "神就照着自己的形像造人，乃是照着他的形像造男造女。", "en": "And God created man in his own image, in the image of God created he him; male and female created he them."},
        "28": {"zh": "神就赐福给他们，又对他们说：要生养众多，遍满地面，治理这地，也要管理海里的鱼、空中的鸟，和地上各样行动的活物。", "en": "And God blessed them: and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it; and have dominion over the fish of the sea, and over the birds of the heavens, and over every living thing that moveth upon the earth."},
        "29": {"zh": "神说：看哪，我将遍地上一切结种子的菜蔬和一切树上所结有核的果子全赐给你们作食物。", "en": "And God said, Behold, I have given you every herb yielding seed, which is upon the face of all the earth, and every tree, in which is the fruit of a tree yielding seed; to you it shall be for food:"},
        "30": {"zh": "至于地上的走兽和空中的飞鸟，并各样爬在地上有生命的物，我将青草赐给它们作食物。事就这样成了。", "en": "and to every beast of the earth, and to every bird of the heavens, and to everything that creepeth upon the earth, wherein there is life, I have given every green herb for food: and it was so."},
        "31": {"zh": "神看着一切所造的都甚好。有晚上，有早晨，是第六日。", "en": "And God saw everything that he had made, and, behold, it was very good. And there was evening and there was morning, the sixth day."}
      },
      "2": {
        "1": {"zh": "天地万物都造齐了。", "en": "And the heavens and the earth were finished, and all the host of them."},
        "2": {"zh": "到第七日，神造物的工已经完毕，就在第七日歇了他一切的工，安息了。", "en": "And on the seventh day God finished his work which he had made; and he rested on the seventh day from all his work which he had made."},
        "3": {"zh": "神赐福给第七日，定为圣日；因为在这日，神歇了他一切创造的工，就安息了。", "en": "And God blessed the seventh day, and hallowed it; because that in it he rested from all his work which God had created and made."},
        "4": {"zh": "创造天地的来历，在耶和华神造天地的日子，乃是这样，", "en": "These are the generations of the heavens and of the earth when they were created, in the day that Jehovah God made earth and heaven."},
        "5": {"zh": "野地还没有草木，田间的菜蔬还没有长起来；因为耶和华神还没有降雨在地上，也没有人耕地，", "en": "And no plant of the field was yet in the earth, and no herb of the field had yet sprung up; for Jehovah God had not caused it to rain upon the earth: and there was not a man to till the ground;"},
        "6": {"zh": "但有雾气从地上腾，滋润遍地。", "en": "but there went up a mist from the earth, and watered the whole face of the ground."},
        "7": {"zh": "耶和华神用地上的尘土造人，将生气吹在他鼻孔里，他就成了有灵的活人，名叫亚当。", "en": "And Jehovah God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul."},
        "8": {"zh": "耶和华神在东方的伊甸立了一个园子，把所造的人安置在那里。", "en": "And Jehovah God planted a garden eastward, in Eden; and there he put the man whom he had formed."},
        "9": {"zh": "耶和华神使各样的树从地里长出来，可以悦人的眼目，其上的果子好作食物。园子当中又有生命树和分别善恶的树。", "en": "And out of the ground made Jehovah God to grow every tree that is pleasant to the sight, and good for food; the tree of life also in the midst of the garden, and the tree of the knowledge of good and evil."},
        "10": {"zh": "有河从伊甸流出来，滋润那园子，从那里分为四道：", "en": "And a river went out of Eden to water the garden; and from thence it was parted, and became four heads."},
        "11": {"zh": "第一道名叫比逊，就是环绕哈腓拉全地的。在那里有金子，", "en": "The name of the first is Pishon: that is it which compasseth the whole land of Havilah, where there is gold;"},
        "12": {"zh": "并且那地的金子是好的；在那里又有珍珠和红玛瑙。", "en": "and the gold of that land is good: there is bdellium and the onyx stone."},
        "13": {"zh": "第二道河名叫基训，就是环绕古实全地的。", "en": "And the name of the second river is Gihon: the same is it that compasseth the whole land of Cush."},
        "14": {"zh": "第三道河名叫底格里斯，流在亚述的东边。第四道河就是幼发拉底河。", "en": "And the name of the third river is Hiddekel: that is it which goeth in front of Assyria. And the fourth river is the Euphrates."},
        "15": {"zh": "耶和华神将那人安置在伊甸园，使他修理，看守。", "en": "And Jehovah God took the man, and put him into the garden of Eden to dress it and to keep it."},
        "16": {"zh": "耶和华神吩咐他说：园中各样树上的果子，你可以随意吃，", "en": "And Jehovah God commanded the man, saying, Of every tree of the garden thou mayest freely eat:"},
        "17": {"zh": "只是分别善恶树上的果子，你不可吃，因为你吃的日子必定死！", "en": "but of the tree of the knowledge of good and evil, thou shalt not eat of it: for in the day that thou eatest thereof thou shalt surely die."},
        "18": {"zh": "耶和华神说：那人独居不好，我要为他造一个配偶帮助他。", "en": "And Jehovah God said, It is not good that the man should be alone; I will make him a help meet for him."},
        "19": {"zh": "耶和华神用土所造成的野地各样走兽和空中各样飞鸟都带到那人面前，看他叫什么。那人怎样叫各样的活物，那就是它的名字。", "en": "And out of the ground Jehovah God formed every beast of the field, and every bird of the heavens; and brought them unto the man to see what he would call them: and whatsoever the man called every living creature, that was the name thereof."},
        "20": {"zh": "那人便给一切牲畜和空中飞鸟、野地走兽都起了名；只是那人没有遇见配偶帮助他。", "en": "And the man gave names to all cattle, and to the birds of the heavens, and to every beast of the field; but for man there was not found a help meet for him."},
        "21": {"zh": "耶和华神使他沉睡，他就睡了；于是取下他的一条肋骨，又把肉合起来。", "en": "And Jehovah God caused a deep sleep to fall upon the man, and he slept; and he took one of his ribs, and closed up the flesh instead thereof:"},
        "22": {"zh": "耶和华神就用那人身上所取的肋骨造成一个女人，领她到那人跟前。", "en": "and the rib, which Jehovah God had taken from the man, made he a woman, and brought her unto the man."},
        "23": {"zh": "那人说：这是我骨中的骨，肉中的肉，可以称她为女人，因为她是从男人身上取出来的。", "en": "And the man said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man."},
        "24": {"zh": "因此，人要离开父母，与妻子连合，二人成为一体。", "en": "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh."},
        "25": {"zh": "当时夫妻二人赤身露体，并不羞耻。", "en": "And they were both naked, the man and his wife, and were not ashamed."}
      },
      "3": {
        "1": {"zh": "耶和华神所造的，惟有蛇比田野一切的活物更狡猾。蛇对女人说：神岂是真说不许你们吃园中所有树上的果子么？", "en": "Now the serpent was more subtle than any beast of the field which Jehovah God had made. And he said unto the woman, Yea, hath God said, Ye shall not eat of any tree of the garden?"},
        "2": {"zh": "女人对蛇说：园中树上的果子，我们可以吃，", "en": "And the woman said unto the serpent, Of the fruit of the trees of the garden we may eat:"},
        "3": {"zh": "惟有园当中那棵树上的果子，神曾说：你们不可吃，也不可摸，免得你们死。", "en": "but of the fruit of the tree which is in the midst of the garden, God hath said, Ye shall not eat of it, neither shall ye touch it, lest ye die."},
        "4": {"zh": "蛇对女人说：你们不一定死；", "en": "And the serpent said unto the woman, Ye shall not surely die:"},
        "5": {"zh": "因为神知道，你们吃的日子眼睛就明亮了，你们便如神能知道善恶。", "en": "for God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as God, knowing good and evil."},
        "6": {"zh": "于是女人见那棵树的果子好作食物，也悦人的眼目，且是可喜爱的，能使人有智慧，就摘下果子来吃了，又给她丈夫，她丈夫也吃了。", "en": "And when the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was to be desired to make one wise, she took of the fruit thereof, and did eat; and she gave also unto her husband with her, and he did eat."},
        "7": {"zh": "他们二人的眼睛就明亮了，才知道自己是赤身露体，便拿无花果树的叶子为自己编做裙子。", "en": "And the eyes of them both were opened, and they knew that they were naked; and they sewed fig-leaves together, and made themselves aprons."},
        "8": {"zh": "天起了凉风，耶和华神在园中行走。那人和他妻子听见神的声音，就藏在园里的树木中，躲避耶和华神的面。", "en": "And they heard the voice of Jehovah God walking in the garden in the cool of the day: and the man and his wife hid themselves from the presence of Jehovah God amongst the trees of the garden."},
        "9": {"zh": "耶和华神呼唤那人，对他说：你在哪里？", "en": "And Jehovah God called unto the man, and said unto him, Where art thou?"},
        "10": {"zh": "他说：我在园中听见你的声音，我就害怕；因为我赤身露体，我便藏了。", "en": "And he said, I heard thy voice in the garden, and I was afraid, because I was naked; and I hid myself."},
        "11": {"zh": "耶和华说：谁告诉你赤身露体呢？莫非你吃了我吩咐你不可吃的那树上的果子么？", "en": "And he said, Who told thee that thou wast naked? Hast thou eaten of the tree whereof I commanded thee that thou shouldest not eat?"},
        "12": {"zh": "那人说：你所赐给我、与我同居的女人，她把那树上的果子给我，我就吃了。", "en": "And the man said, The woman whom thou gavest to be with me, she gave me of the tree, and I did eat."},
        "13": {"zh": "耶和华神对女人说：你做的是什么事呢？女人说：那蛇引诱我，我就吃了。", "en": "And Jehovah God said unto the woman, What is this thou hast done? And the woman said, The serpent beguiled me, and I did eat."},
        "14": {"zh": "耶和华神对蛇说：你既做了这事，就必受咒诅，比一切的牲畜野兽更甚。你必用肚子行走，终身吃土。", "en": "And Jehovah God said unto the serpent, Because thou hast done this, cursed art thou above all cattle, and above every beast of the field; upon thy belly shalt thou go, and dust shalt thou eat all the days of thy life:"},
        "15": {"zh": "我又要叫你和女人彼此为仇；你的后裔和女人的后裔也彼此为仇。女人的后裔要伤你的头；你要伤他的脚跟。", "en": "and I will put enmity between thee and the woman, and between thy seed and her seed: he shall bruise thy head, and thou shalt bruise his heel."},
        "16": {"zh": "又对女人说：我必多多加增你怀胎的苦楚；你生产儿女必多受苦楚。你必恋慕你丈夫；你丈夫必管辖你。", "en": "Unto the woman he said, I will greatly multiply thy pain and thy conception; in pain thou shalt bring forth children; and thy desire shall be to thy husband, and he shall rule over thee."},
        "17": {"zh": "又对亚当说：你既听从妻子的话，吃了我所吩咐你不可吃的那树上的果子，地必为你的缘故受咒诅；你必终身劳苦才能从地里得吃的。", "en": "And unto Adam he said, Because thou hast hearkened unto the voice of thy wife, and hast eaten of the tree, of which I commanded thee, saying, Thou shalt not eat of it: cursed is the ground for thy sake; in toil shalt thou eat of it all the days of thy life;"},
        "18": {"zh": "地必给你长出荆棘和蒺藜来；你也要吃田间的菜蔬。", "en": "thorns also and thistles shall it bring forth to thee; and thou shalt eat the herb of the field;"},
        "19": {"zh": "你必汗流满面才得糊口，直到你归了土，因为你是从土而出的。你本是尘土，仍要归于尘土。", "en": "in the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return."},
        "20": {"zh": "亚当给他妻子起名叫夏娃，因为她是众生之母。", "en": "And the man called his wife's name Eve; because she was the mother of all living."},
        "21": {"zh": "耶和华神为亚当和他妻子用皮子做衣服给他们穿。", "en": "And Jehovah God made for Adam and for his wife coats of skins, and clothed them."},
        "22": {"zh": "耶和华神说：那人已经与我们相似，能知道善恶；现在恐怕他伸手又摘生命树的果子吃，就永远活着。", "en": "And Jehovah God said, Behold, the man is become as one of us, to know good and evil; and now, lest he put forth his hand, and take also of the tree of life, and eat, and live for ever—"},
        "23": {"zh": "耶和华神便打发他出伊甸园去，耕种他所自出之土。", "en": "therefore Jehovah God sent him forth from the garden of Eden, to till the ground from whence he was taken."},
        "24": {"zh": "于是把他赶出去了；又在伊甸园的东边安设基路伯和四面转动发火焰的剑，要把守生命树的道路。", "en": "So he drove out the man; and he placed at the east of the garden of Eden the Cherubim, and the flame of a sword which turned every way, to keep the way of the tree of life."}
      },
      "4": {
        "1": {"zh": "有一日，那人和他妻子夏娃同房，夏娃就怀孕，生了该隐，便说：耶和华使我得了一个男子。", "en": "And the man knew Eve his wife; and she conceived, and bare Cain, and said, I have gotten a man with the help of Jehovah."},
        "2": {"zh": "又生了该隐的兄弟亚伯。亚伯是牧羊的；该隐是种地的。", "en": "And again she bare his brother Abel. And Abel was a keeper of sheep, but Cain was a tiller of the ground."},
        "3": {"zh": "有一日，该隐拿地里的出产为供物献给耶和华；", "en": "And in process of time it came to pass, that Cain brought of the fruit of the ground an offering unto Jehovah."},
        "4": {"zh": "亚伯也将他羊群中头生的和羊的脂油献上。耶和华看中了亚伯和他的供物，", "en": "And Abel, he also brought of the firstlings of his flock and of the fat thereof. And Jehovah had respect unto Abel and to his offering:"},
        "5": {"zh": "只是看不中该隐和他的供物。该隐就大大的发怒，变了脸色。", "en": "but unto Cain and to his offering he had not respect. And Cain was very wroth, and his countenance fell."},
        "6": {"zh": "耶和华对该隐说：你为什么发怒呢？你为什么变了脸色呢？", "en": "And Jehovah said unto Cain, Why art thou wroth? and why is thy countenance fallen?"},
        "7": {"zh": "你若行得好，岂不蒙悦纳？你若行得不好，罪就伏在门前。它必恋慕你，你却要制伏它。", "en": "If thou doest well, shalt thou not be accepted? and if thou doest not well, sin coucheth at the door: and unto thee shall be its desire, but thou shalt rule over it."},
        "8": {"zh": "该隐与他兄弟亚伯说话；二人正在田间。该隐起来打他兄弟亚伯，把他杀了。", "en": "And Cain told Abel his brother. And it came to pass, when they were in the field, that Cain rose up against Abel his brother, and slew him."},
        "9": {"zh": "耶和华对该隐说：你兄弟亚伯在哪里？他说：我不知道！我岂是看守我兄弟的么？", "en": "And Jehovah said unto Cain, Where is Abel thy brother? And he said, I know not: am I my brother's keeper?"},
        "10": {"zh": "耶和华说：你做了什么事呢？你兄弟的血有声音从地里向我哀告。", "en": "And he said, What hast thou done? the voice of thy brother's blood crieth unto me from the ground."},
        "11": {"zh": "地开了口，从你手里接受你兄弟的血。现在你必从这地受咒诅。", "en": "And now cursed art thou from the ground, which hath opened its mouth to receive thy brother's blood from thy hand;"},
        "12": {"zh": "你种地，地不再给你效力；你必流离飘荡在地上。", "en": "when thou tillest the ground, it shall not henceforth yield unto thee its strength; a fugitive and a wanderer shalt thou be in the earth."},
        "13": {"zh": "该隐对耶和华说：我的刑罚太重，过于我所能当的。", "en": "And Cain said unto Jehovah, My punishment is greater than I can bear."},
        "14": {"zh": "你如今赶逐我离开这地，以致不见你面；我必流离飘荡在地上，凡遇见我的必杀我。", "en": "Behold, thou hast driven me out this day from the face of the ground; and from thy face shall I be hid; and I shall be a fugitive and a wanderer in the earth, and it will come to pass, that whosoever findeth me will slay me."},
        "15": {"zh": "耶和华对他说：凡杀该隐的，必遭报七倍。耶和华就给该隐立一个记号，免得人遇见他就杀他。", "en": "And Jehovah said unto him, Therefore whosoever slayeth Cain, vengeance shall be taken on him sevenfold. And Jehovah appointed a sign for Cain, lest any finding him should smite him."},
        "16": {"zh": "于是该隐离开耶和华的面，去住在伊甸东边挪得之地。", "en": "And Cain went out from the presence of Jehovah, and dwelt in the land of Nod, on the east of Eden."},
        "17": {"zh": "该隐与妻子同房，他妻子就怀孕，生了以诺。该隐建造了一座城，就按着他儿子的名将那城叫做以诺。", "en": "And Cain knew his wife; and she conceived, and bare Enoch: and he builded a city, and called the name of the city, after the name of his son, Enoch."},
        "18": {"zh": "以诺生以拿；以拿生米户雅利；米户雅利生玛土撒利；玛土撒利生拉麦。", "en": "And unto Enoch was born Irad: and Irad begat Mehujael: and Mehujael begat Methushael: and Methushael begat Lamech."},
        "19": {"zh": "拉麦娶了两个妻：一个名叫亚大，一个名叫洗拉。", "en": "And Lamech took unto him two wives: the name of the one was Adah, and the name of the other Zillah."},
        "20": {"zh": "亚大生雅八；雅八就是住帐棚、牧养牲畜之人的祖师。", "en": "And Adah bare Jabal: he was the father of such as dwell in tents and have cattle."},
        "21": {"zh": "雅八的兄弟名叫犹八；他是一切弹琴吹箫之人的祖师。", "en": "And his brother's name was Jubal: he was the father of all such as handle the harp and pipe."},
        "22": {"zh": "洗拉又生了土八该隐；他是打造各样铜铁利器的。土八该隐的妹子是拿玛。", "en": "And Zillah, she also bare Tubal-cain, the forger of every cutting instrument of brass and iron: and the sister of Tubal-cain was Naamah."},
        "23": {"zh": "拉麦对他两个妻子说：亚大、洗拉，听我的声音；拉麦的妻子，细听我的话语：壮年人伤我，我把他杀了；少年人损我，我把他害了。", "en": "And Lamech said unto his wives: Adah and Zillah, hear my voice; Ye wives of Lamech, hearken unto my speech: For I have slain a man for wounding me, And a young man for bruising me:"},
        "24": {"zh": "若杀该隐，遭报七倍，杀拉麦，必遭报七十七倍。", "en": "If Cain shall be avenged sevenfold, Truly Lamech seventy and sevenfold."},
        "25": {"zh": "亚当又与妻子同房，她就生了一个儿子，起名叫塞特，意思说：神另给我立了一个儿子代替亚伯，因为该隐杀了他。", "en": "And Adam knew his wife again; and she bare a son, and called his name Seth: For, said she, God hath appointed me another seed instead of Abel; for Cain slew him."},
        "26": {"zh": "塞特也生了一个儿子，起名叫以挪士。那时候，人才求告耶和华的名。", "en": "And to Seth, to him also there was born a son; and he called his name Enosh. Then began men to call upon the name of Jehovah."}
      },
      "5": {
        "1": {"zh": "亚当的后代记在下面。当神造人的日子，是照着自己的样式造的，", "en": "This is the book of the generations of Adam. In the day that God created man, in the likeness of God made he him;"},
        "2": {"zh": "并且造男造女。在他们被造的日子，神赐福给他们，称他们为人。", "en": "male and female created he them, and blessed them, and called their name Adam, in the day when they were created."},
        "3": {"zh": "亚当活到一百三十岁，生了一个儿子，形像样式和自己相似，就给他起名叫塞特。", "en": "And Adam lived a hundred and thirty years, and begat a son in his own likeness, after his image; and called his name Seth:"},
        "4": {"zh": "亚当生塞特之后，又在世八百年，并且生儿养女。", "en": "and the days of Adam after he begat Seth were eight hundred years: and he begat sons and daughters."},
        "5": {"zh": "亚当共活了九百三十岁就死了。", "en": "And all the days that Adam lived were nine hundred and thirty years: and he died."},
        "6": {"zh": "塞特活到一百零五岁，生了以挪士。", "en": "And Seth lived a hundred and five years, and begat Enosh:"},
        "7": {"zh": "塞特生以挪士之后，又活了八百零七年，并且生儿养女。", "en": "and Seth lived after he begat Enosh eight hundred and seven years, and begat sons and daughters:"},
        "8": {"zh": "塞特共活了九百一十二岁就死了。", "en": "and all the days of Seth were nine hundred and twelve years: and he died."},
        "9": {"zh": "以挪士活到九十岁，生了该南。", "en": "And Enosh lived ninety years, and begat Kenan:"},
        "10": {"zh": "以挪士生该南之后，又活了八百一十五年，并且生儿养女。", "en": "and Enosh lived after he begat Kenan eight hundred and fifteen years, and begat sons and daughters:"},
        "11": {"zh": "以挪士共活了九百零五岁就死了。", "en": "and all the days of Enosh were nine hundred and five years: and he died."},
        "12": {"zh": "该南活到七十岁，生了玛勒列。", "en": "And Kenan lived seventy years, and begat Mahalalel:"},
        "13": {"zh": "该南生玛勒列之后，又活了八百四十年，并且生儿养女。", "en": "and Kenan lived after he begat Mahalalel eight hundred and forty years, and begat sons and daughters:"},
        "14": {"zh": "该南共活了九百一十岁就死了。", "en": "and all the days of Kenan were nine hundred and ten years: and he died."},
        "15": {"zh": "玛勒列活到六十五岁，生了雅列。", "en": "And Mahalalel lived sixty and five years, and begat Jared:"},
        "16": {"zh": "玛勒列生雅列之后，又活了八百三十年，并且生儿养女。", "en": "and Mahalalel lived after he begat Jared eight hundred and thirty years, and begat sons and daughters:"},
        "17": {"zh": "玛勒列共活了八百九十五岁就死了。", "en": "and all the days of Mahalalel were eight hundred ninety and five years: and he died."},
        "18": {"zh": "雅列活到一百六十二岁，生了以诺。", "en": "And Jared lived a hundred sixty and two years, and begat Enoch:"},
        "19": {"zh": "雅列生以诺之后，又活了八百年，并且生儿养女。", "en": "and Jared lived after he begat Enoch eight hundred years, and begat sons and daughters:"},
        "20": {"zh": "雅列共活了九百六十二岁就死了。", "en": "and all the days of Jared were nine hundred sixty and two years: and he died."},
        "21": {"zh": "以诺活到六十五岁，生了玛土撒拉。", "en": "And Enoch lived sixty and five years, and begat Methuselah:"},
        "22": {"zh": "以诺生玛土撒拉之后，与神同行三百年，并且生儿养女。", "en": "and Enoch walked with God after he begat Methuselah three hundred years, and begat sons and daughters:"},
        "23": {"zh": "以诺共活了三百六十五岁。", "en": "and all the days of Enoch were three hundred sixty and five years:"},
        "24": {"zh": "以诺与神同行，神将他取去，他就不在世了。", "en": "and Enoch walked with God: and he was not; for God took him."},
        "25": {"zh": "玛土撒拉活到一百八十七岁，生了拉麦。", "en": "And Methuselah lived a hundred eighty and seven years, and begat Lamech:"},
        "26": {"zh": "玛土撒拉生拉麦之后，又活了七百八十二年，并且生儿养女。", "en": "and Methuselah lived after he begat Lamech seven hundred eighty and two years, and begat sons and daughters:"},
        "27": {"zh": "玛土撒拉共活了九百六十九岁就死了。", "en": "and all the days of Methuselah were nine hundred sixty and nine years: and he died."},
        "28": {"zh": "拉麦活到一百八十二岁，生了一个儿子，", "en": "And Lamech lived a hundred eighty and two years, and begat a son:"},
        "29": {"zh": "给他起名叫挪亚，说：这个儿子必为我们的操作和手中的劳苦安慰我们；这操作劳苦是因为耶和华咒诅地。", "en": "and he called his name Noah, saying, This same shall comfort us in our work and in the toil of our hands, because of the ground which Jehovah hath cursed."},
        "30": {"zh": "拉麦生挪亚之后，又活了五百九十五年，并且生儿养女。", "en": "And Lamech lived after he begat Noah five hundred ninety and five years, and begat sons and daughters:"},
        "31": {"zh": "拉麦共活了七百七十七岁就死了。", "en": "And all the days of Lamech were seven hundred seventy and seven years: and he died."},
        "32": {"zh": "挪亚五百岁生了闪、含、雅弗。", "en": "And Noah was five hundred years old: and Noah begat Shem, Ham, and Japheth."}
      },
      "6": {
        "1": {"zh": "当人在世上多起来、又生女儿的时候，", "en": "And it came to pass, when men began to multiply on the face of the ground, and daughters were born unto them,"},
        "2": {"zh": "神的儿子们看见人的女子美貌，就随意挑选，娶来为妻。", "en": "that the sons of God saw the daughters of men that they were fair; and they took them wives of all that they chose."},
        "3": {"zh": "耶和华说：人既属乎血气，我的灵就不永远住在他里面；然而他的日子还可到一百二十年。", "en": "And Jehovah said, My Spirit shall not strive with man for ever, for that he also is flesh: yet shall his days be a hundred and twenty years."},
        "4": {"zh": "那时候有伟人在地上，后来神的儿子们和人的女子们交合生子；那就是上古英武有名的人。", "en": "The Nephilim were in the earth in those days, and also after that, when the sons of God came unto the daughters of men, and they bare children to them: the same were the mighty men that were of old, the men of renown."},
        "5": {"zh": "耶和华见人在地上罪恶很大，终日所思想的尽都是恶，", "en": "And Jehovah saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually."},
        "6": {"zh": "耶和华就后悔造人在地上，心中忧伤。", "en": "And it repented Jehovah that he had made man on the earth, and it grieved him at his heart."},
        "7": {"zh": "耶和华说：我要将所造的人和走兽，并昆虫，以及空中的飞鸟，都从地上除灭，因为我造他们后悔了。", "en": "And Jehovah said, I will destroy man whom I have created from the face of the ground; both man, and beast, and creeping things, and birds of the heavens; for it repenteth me that I have made them."},
        "8": {"zh": "惟有挪亚在耶和华眼前蒙恩。", "en": "But Noah found favor in the eyes of Jehovah."},
        "9": {"zh": "挪亚的后代记在下面。挪亚是个义人，在当时的世代是个完全人。挪亚与神同行。", "en": "These are the generations of Noah. Noah was a righteous man, and perfect in his generations: Noah walked with God."},
        "10": {"zh": "挪亚生了三个儿子，就是闪、含、雅弗。", "en": "And Noah begat three sons, Shem, Ham, and Japheth."},
        "11": {"zh": "世界在神面前败坏，地上满了强暴。", "en": "And the earth was corrupt before God, and the earth was filled with violence."},
        "12": {"zh": "神观看世界，见是败坏了；凡有血气的人在地上都败坏了行为。", "en": "And God saw the earth, and, behold, it was corrupt; for all flesh had corrupted their way upon the earth."},
        "13": {"zh": "神就对挪亚说：凡有血气的人，他的尽头已经来到我面前；因为地上满了他们的强暴，我要把他们和地一并毁灭。", "en": "And God said unto Noah, The end of all flesh is come before me; for the earth is filled with violence through them; and, behold, I will destroy them with the earth."},
        "14": {"zh": "你要用歌斐木造一只方舟，分一间一间地造，里外抹上松香。", "en": "Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch."},
        "15": {"zh": "方舟的造法乃是这样：要长三百肘，宽五十肘，高三十肘。", "en": "And this is how thou shalt make it: the length of the ark three hundred cubits, the breadth of it fifty cubits, and the height of it thirty cubits."},
        "16": {"zh": "方舟上边要留透光处，高一肘。方舟的门要开在旁边。方舟要分上、中、下三层。", "en": "A light shalt thou make to the ark, and to a cubit shalt thou finish it upward; and the door of the ark shalt thou set in the side thereof; with lower, second, and third stories shalt thou make it."},
        "17": {"zh": "看哪，我要使洪水泛滥在地上，毁灭天下；凡地上有血肉、有气息的活物，无一不死。", "en": "And I, behold, I do bring the flood of waters upon this earth, to destroy all flesh, wherein is the breath of life, from under heaven; everything that is in the earth shall die."},
        "18": {"zh": "我却要与你立约；你同你的妻，与儿子儿妇，都要进入方舟。", "en": "But I will establish my covenant with thee; and thou shalt come into the ark, thou, and thy sons, and thy wife, and thy sons' wives with thee."},
        "19": {"zh": "凡有血肉的活物，每样两个，一公一母，你要带进方舟，好在你那里保全生命。", "en": "And of every living thing of all flesh, two of every sort shalt thou bring into the ark, to keep them alive with thee; they shall be male and female."},
        "20": {"zh": "飞鸟各从其类，牲畜各从其类，地上的昆虫各从其类，每样两个，要到你那里，好保全生命。", "en": "Of the birds after their kind, and of the cattle after their kind, of every creeping thing of the ground after its kind, two of every sort shall come unto thee, to keep them alive."},
        "21": {"zh": "你要拿各样食物积蓄起来，好作你和它们的食物。", "en": "And take thou unto thee of all food that is eaten, and gather it to thee; and it shall be for food for thee, and for them."},
        "22": {"zh": "挪亚就这样行。凡神所吩咐的，他都照样行了。", "en": "Thus did Noah; according to all that God commanded him, so did he."}
      },
      "7": {
        "1": {"zh": "耶和华对挪亚说：你和你的全家都要进入方舟；因为在这世代中，我见你在我面前是义人。", "en": "And Jehovah said unto Noah, Come thou and all thy house into the ark; for thee have I seen righteous before me in this generation."},
        "2": {"zh": "凡洁净的畜类，你要带七公七母；不洁净的畜类，你要带一公一母；", "en": "Of every clean beast thou shalt take to thee seven and seven, the male and his female; and of the beasts that are not clean two, the male and his female:"},
        "3": {"zh": "空中的飞鸟也要带七公七母，可以留种，活在全地上；", "en": "of the birds also of the heavens, seven and seven, male and female, to keep seed alive upon the face of all the earth."},
        "4": {"zh": "因为再过七天，我要降雨在地上四十昼夜，把我所造的各种活物都从地上除灭。", "en": "For yet seven days, and I will cause it to rain upon the earth forty days and forty nights; and every living thing that I have made will I destroy from off the face of the ground."},
        "5": {"zh": "挪亚就遵着耶和华所吩咐的行了。", "en": "And Noah did according unto all that Jehovah commanded him."},
        "6": {"zh": "当洪水泛滥在地上的时候，挪亚整六百岁。", "en": "And Noah was six hundred years old when the flood of waters was upon the earth."},
        "7": {"zh": "挪亚就同他的妻和儿子儿妇都进入方舟，躲避洪水。", "en": "And Noah went in, and his sons, and his wife, and his sons' wives with him, into the ark, because of the waters of the flood."},
        "8": {"zh": "洁净的畜类和不洁净的畜类，飞鸟并地上一切的昆虫，", "en": "Of clean beasts, and of beasts that are not clean, and of birds, and of everything that creepeth upon the ground,"},
        "9": {"zh": "都是一对一对地，有公有母，到挪亚那里进入方舟，正如神所吩咐挪亚的。", "en": "there went in two and two unto Noah into the ark, male and female, as God commanded Noah."},
        "10": {"zh": "过了那七天，洪水泛滥在地上。", "en": "And it came to pass after the seven days, that the waters of the flood were upon the earth."},
        "11": {"zh": "当挪亚六百岁，二月十七日那一天，大渊的泉源都裂开了，天上的窗户也敞开了，", "en": "In the six hundredth year of Noah's life, in the second month, on the seventeenth day of the month, on the same day were all the fountains of the great deep broken up, and the windows of heaven were opened."},
        "12": {"zh": "四十昼夜降大雨在地上。", "en": "And the rain was upon the earth forty days and forty nights."},
        "13": {"zh": "正当那日，挪亚和他三个儿子闪、含、雅弗，并挪亚的妻子和三个儿妇，都进入方舟。", "en": "In the selfsame day entered Noah, and Shem, and Ham, and Japheth, the sons of Noah, and Noah's wife, and the three wives of his sons with them, into the ark;"},
        "14": {"zh": "他们和百兽，各从其类，一切牲畜，各从其类，爬在地上的昆虫，各从其类，一切禽鸟，各从其类，都进入方舟。", "en": "they, and every beast after its kind, and all the cattle after their kind, and every creeping thing that creepeth upon the earth after its kind, and every bird after its kind, every bird of every sort."},
        "15": {"zh": "凡有血肉、有气息的活物，都一对一对地到挪亚那里，进入方舟。", "en": "And they went in unto Noah into the ark, two and two of all flesh wherein is the breath of life."},
        "16": {"zh": "凡有血肉进入方舟的，都是有公有母，正如神所吩咐挪亚的。耶和华就把他关在方舟里头。", "en": "And they that went in, went in male and female of all flesh, as God commanded him: and Jehovah shut him in."},
        "17": {"zh": "洪水泛滥在地上四十天，水往上长，把方舟从地上漂起。", "en": "And the flood was forty days upon the earth; and the waters increased, and bare up the ark, and it was lifted up above the earth."},
        "18": {"zh": "水势浩大，在地上大大地往上长，方舟在水面上漂来漂去。", "en": "And the waters prevailed, and increased greatly upon the earth; and the ark went upon the face of the waters."},
        "19": {"zh": "水势在地上极其浩大，天下的高山都淹没了。", "en": "And the waters prevailed exceedingly upon the earth; and all the high mountains that were under the whole heaven were covered."},
        "20": {"zh": "水势比山高过十五肘，山岭都淹没了。", "en": "Fifteen cubits upward did the waters prevail; and the mountains were covered."},
        "21": {"zh": "凡在地上有血肉的动物，就是飞鸟、牲畜、走兽，和爬在地上的昆虫，以及所有的人，都死了。", "en": "And all flesh died that moved upon the earth, both birds, and cattle, and beasts, and every creeping thing that creepeth upon the earth, and every man:"},
        "22": {"zh": "凡在旱地上、鼻孔有气息的生灵都死了。", "en": "all in whose nostrils was the breath of the spirit of life, of all that was on the dry land, died."},
        "23": {"zh": "凡地上各类的活物，连人带牲畜、昆虫，以及空中的飞鸟，都从地上除灭了，只留下挪亚和那些与他同在方舟里的。", "en": "And every living thing was destroyed that was upon the face of the ground, both man, and cattle, and creeping things, and birds of the heavens; and they were destroyed from the earth: and Noah only was left, and they that were with him in the ark."},
        "24": {"zh": "水势浩大，在地上共一百五十天。", "en": "And the waters prevailed upon the earth a hundred and fifty days."}
      },
      "8": {
        "1": {"zh": "神记念挪亚和挪亚方舟里的一切走兽牲畜。神叫风吹地，水势渐落。", "en": "And God remembered Noah, and all the beasts, and all the cattle that were with him in the ark: and God made a wind to pass over the earth, and the waters assuaged;"},
        "2": {"zh": "渊源和天上的窗户都闭塞了，天上的大雨也止住了。", "en": "the fountains also of the deep and the windows of heaven were stopped, and the rain from heaven was restrained;"},
        "3": {"zh": "水从地上渐退。过了一百五十天，水就渐消。", "en": "and the waters returned from off the earth continually: and after the end of a hundred and fifty days the waters decreased."},
        "4": {"zh": "七月十七日，方舟停在亚拉腊山上。", "en": "And the ark rested in the seventh month, on the seventeenth day of the month, upon the mountains of Ararat."},
        "5": {"zh": "水又渐消，到十月初一日，山顶都现出来了。", "en": "And the waters decreased continually until the tenth month: in the tenth month, on the first day of the month, were the tops of the mountains seen."},
        "6": {"zh": "过了四十天，挪亚开了方舟的窗户，", "en": "And it came to pass at the end of forty days, that Noah opened the window of the ark which he had made:"},
        "7": {"zh": "放出一只乌鸦去；那乌鸦飞来飞去，直到地上的水都干了。", "en": "and he sent forth a raven, and it went forth to and fro, until the waters were dried up from off the earth."},
        "8": {"zh": "他又放出一只鸽子去，要看看水从地上退了没有。", "en": "And he sent forth a dove from him, to see if the waters were abated from off the face of the ground;"},
        "9": {"zh": "但遍地上都是水，鸽子找不着落脚之地，就回到方舟挪亚那里，挪亚伸手把鸽子接进方舟来。", "en": "but the dove found no rest for the sole of her foot, and she returned unto him to the ark; for the waters were on the face of the whole earth: and he put forth his hand, and took her, and brought her in unto him into the ark."},
        "10": {"zh": "他又等了七天，再把鸽子从方舟放出去。", "en": "And he stayed yet other seven days; and again he sent forth the dove out of the ark;"},
        "11": {"zh": "到了晚上，鸽子回到他那里，嘴里叼着一个新拧下来的橄榄叶子，挪亚就知道地上的水退了。", "en": "and the dove came in to him at eventide; and, lo, in her mouth an olive-leaf plucked off: so Noah knew that the waters were abated from off the earth."},
        "12": {"zh": "他又等了七天，放出鸽子去，鸽子就不再回来了。", "en": "And he stayed yet other seven days, and sent forth the dove; and she returned not again unto him any more."},
        "13": {"zh": "到挪亚六百零一岁，正月初一日，地上的水都干了。挪亚撤去方舟的盖观看，便见地面上干了。", "en": "And it came to pass in the six hundred and first year, in the first month, the first day of the month, the waters were dried up from off the earth: and Noah removed the covering of the ark, and looked, and, behold, the face of the ground was dried."},
        "14": {"zh": "到了二月二十七日，地就都干了。", "en": "And in the second month, on the seven and twentieth day of the month, was the earth dry."},
        "15": {"zh": "神对挪亚说：", "en": "And God spake unto Noah, saying,"},
        "16": {"zh": "你和你的妻子、儿子、儿妇都可以出方舟。", "en": "Go forth from the ark, thou, and thy wife, and thy sons, and thy sons' wives with thee."},
        "17": {"zh": "在你那里凡有血肉的活物，就是飞鸟、牲畜，和一切爬在地上的昆虫，都要带出来，叫它在地上多多滋生，大大兴旺。", "en": "Bring forth with thee every living thing that is with thee of all flesh, both birds, and cattle, and every creeping thing that creepeth upon the earth, that they may breed abundantly in the earth, and be fruitful, and multiply upon the earth."},
        "18": {"zh": "于是挪亚和他的妻子、儿子、儿妇都出来了。", "en": "And Noah went forth, and his sons, and his wife, and his sons' wives with him:"},
        "19": {"zh": "一切走兽、昆虫、飞鸟，和地上所有的动物，各从其类，也都出了方舟。", "en": "every beast, every creeping thing, and every bird, whatsoever moveth upon the earth, after their families, went forth out of the ark."},
        "20": {"zh": "挪亚为耶和华筑了一座坛，拿各类洁净的牲畜、飞鸟献在坛上为燔祭。", "en": "And Noah builded an altar unto Jehovah, and took of every clean beast, and of every clean bird, and offered burnt-offerings on the altar."},
        "21": {"zh": "耶和华闻那馨香之气，就心里说：我不再因人的缘故咒诅地（人从小时心里怀着恶念），也不再按着我才行的灭各种的活物了。", "en": "And Jehovah smelled the sweet savor; and Jehovah said in his heart, I will not again curse the ground any more for man's sake, for that the imagination of man's heart is evil from his youth; neither will I again smite any more every thing living, as I have done."},
        "22": {"zh": "地还存留的时候，稼穑、寒暑、冬夏、昼夜就永不停息了。", "en": "While the earth remaineth, seedtime and harvest, and cold and heat, and summer and winter, and day and night shall not cease."}
      },
      "9": {
        "1": {"zh": "神赐福给挪亚和他的儿子，对他们说：你们要生养众多，遍满了地。", "en": "And God blessed Noah and his sons, and said unto them, Be fruitful, and multiply, and replenish the earth."},
        "2": {"zh": "凡地上的走兽和空中的飞鸟都必惊恐，惧怕你们，连地上一切的昆虫并海里一切的鱼都交付你们的手。", "en": "And the fear of you and the dread of you shall be upon every beast of the earth, and upon every bird of the heavens; with all wherewith the ground teemeth, and all the fishes of the sea, into your hand are they delivered."},
        "3": {"zh": "凡活着的动物都可以作你们的食物。这一切我都赐给你们，如同菜蔬一样。", "en": "Every moving thing that liveth shall be food for you; as the green herb have I given you all."},
        "4": {"zh": "惟独肉带着血，那就是它的生命，你们不可吃。", "en": "But flesh with the life thereof, which is the blood thereof, shall ye not eat."},
        "5": {"zh": "流你们血、害你们命的，无论是兽是人，我必讨他的罪，就是向各人的弟兄也是如此。", "en": "And surely your blood, the blood of your lives, will I require; at the hand of every beast will I require it: and at the hand of man, even at the hand of every man's brother, will I require the life of man."},
        "6": {"zh": "凡流人血的，他的血也必被人所流，因为神造人是照自己的形像造的。", "en": "Whoso sheddeth man's blood, by man shall his blood be shed: for in the image of God made he man."},
        "7": {"zh": "你们要生养众多，在地上昌盛繁茂。", "en": "And you, be ye fruitful, and multiply; bring forth abundantly in the earth, and multiply therein."},
        "8": {"zh": "神晓谕挪亚和他的儿子说：", "en": "And God spake unto Noah, and to his sons with him, saying,"},
        "9": {"zh": "我与你们和你们的后裔立约，", "en": "And I, behold, I establish my covenant with you, and with your seed after you;"},
        "10": {"zh": "并与你们这里的一切活物，就是飞鸟、牲畜、走兽，凡从方舟里出来的活物立约。", "en": "and with every living creature that is with you, the birds, the cattle, and every beast of the earth with you; of all that go out of the ark, even every beast of the earth."},
        "11": {"zh": "我与你们立约，凡有血肉的，不再被洪水灭绝，也不再有洪水毁坏地了。", "en": "And I will establish my covenant with you; neither shall all flesh be cut off any more by the waters of the flood; neither shall there any more be a flood to destroy the earth."},
        "12": {"zh": "神说：我与你们并你们这里的各样活物所立的永约是有记号的。", "en": "And God said, This is the token of the covenant which I make between me and you and every living creature that is with you, for perpetual generations:"},
        "13": {"zh": "我把虹放在云彩中，这就可作我与地立约的记号了。", "en": "I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth."},
        "14": {"zh": "我使云彩盖地的时候，必有虹现在云彩中，", "en": "And it shall come to pass, when I bring a cloud over the earth, that the bow shall be seen in the cloud,"},
        "15": {"zh": "我便记念我与你们和各样有血肉的活物所立的约，水就再不泛滥、毁坏一切有血肉的物了。", "en": "and I will remember my covenant, which is between me and you and every living creature of all flesh; and the waters shall no more become a flood to destroy all flesh."},
        "16": {"zh": "虹必现在云彩中，我看见，就要记念我与地上各样有血肉的活物所立的永约。", "en": "And the bow shall be in the cloud; and I will look upon it, that I may remember the everlasting covenant between God and every living creature of all flesh that is upon the earth."},
        "17": {"zh": "神对挪亚说：这就是我与地上一切有血肉之物立约的记号了。", "en": "And God said unto Noah, This is the token of the covenant which I have established between me and all flesh that is upon the earth."},
        "18": {"zh": "出方舟挪亚的儿子就是闪、含、雅弗。含是迦南的父亲。", "en": "And the sons of Noah, that went forth from the ark, were Shem, and Ham, and Japheth: and Ham is the father of Canaan."},
        "19": {"zh": "这是挪亚的三个儿子，他们的后裔分散在全地。", "en": "These three were the sons of Noah: and of these was the whole earth overspread."},
        "20": {"zh": "挪亚作起农夫来，栽了一个葡萄园。", "en": "And Noah began to be a husbandman, and planted a vineyard:"},
        "21": {"zh": "他喝了园中的酒便醉了，在帐棚里赤着身子。", "en": "and he drank of the wine, and was drunken; and he was uncovered within his tent."},
        "22": {"zh": "迦南的父亲含看见他父亲赤身，就到外边告诉他两个弟兄。", "en": "And Ham, the father of Canaan, saw the nakedness of his father, and told his two brethren without."},
        "23": {"zh": "于是闪和雅弗拿件衣服搭在肩上，倒退着进去，给他父亲盖上；他们背着脸就看不见父亲的赤身。", "en": "And Shem and Japheth took a garment, and laid it upon both their shoulders, and went backward, and covered the nakedness of their father; and their faces were backward, and they saw not their father's nakedness."},
        "24": {"zh": "挪亚醒了酒，知道小儿子向他所做的事，", "en": "And Noah awoke from his wine, and knew what his youngest son had done unto him."},
        "25": {"zh": "就说：迦南当受咒诅，必给他弟兄作奴仆的奴仆；", "en": "And he said, Cursed be Canaan; A servant of servants shall he be unto his brethren."},
        "26": {"zh": "又说：耶和华闪的神是应当称颂的！愿迦南作闪的奴仆。", "en": "And he said, Blessed be Jehovah, the God of Shem; And let Canaan be his servant."},
        "27": {"zh": "愿神使雅弗扩张，使他住在闪的帐棚里；又愿迦南作他的奴仆。", "en": "God enlarge Japheth, And let him dwell in the tents of Shem; And let Canaan be his servant."},
        "28": {"zh": "洪水以后，挪亚又活了三百五十年。", "en": "And Noah lived after the flood three hundred and fifty years."},
        "29": {"zh": "挪亚共活了九百五十岁就死了。", "en": "And all the days of Noah were nine hundred and fifty years: and he died."}
      },
      "10": {
        "1": {"zh": "挪亚的儿子闪、含、雅弗的后代记在下面。洪水以后，他们都生了儿子。", "en": "Now these are the generations of the sons of Noah, namely, of Shem, Ham, and Japheth: and unto them were sons born after the flood."},
        "2": {"zh": "雅弗的儿子是歌篾、玛各、玛代、雅完、土巴、米设、提拉。", "en": "The sons of Japheth: Gomer, and Magog, and Madai, and Javan, and Tubal, and Meshech, and Tiras."},
        "3": {"zh": "歌篾的儿子是亚实基拿、利法、陀迦玛。", "en": "And the sons of Gomer: Ashkenaz, and Riphath, and Togarmah."},
        "4": {"zh": "雅完的儿子是以利沙、他施、基提、多单。", "en": "And the sons of Javan: Elishah, and Tarshish, Kittim, and Dodanim."},
        "5": {"zh": "这些人的后裔将各国的地土、海岛分开居住，各随各的方言、宗族立国。", "en": "Of these were the isles of the nations divided in their lands, every one after his tongue, after their families, in their nations."},
        "6": {"zh": "含的儿子是古实、麦西、弗、迦南。", "en": "And the sons of Ham: Cush, and Mizraim, and Put, and Canaan."},
        "7": {"zh": "古实的儿子是西巴、哈腓拉、撒弗他、拉玛、撒弗提迦。拉玛的儿子是示巴、底但。", "en": "And the sons of Cush: Seba, and Havilah, and Sabtah, and Raamah, and Sabteca; and the sons of Raamah: Sheba, and Dedan."},
        "8": {"zh": "古实又生宁录，他为世上英雄之首。", "en": "And Cush begat Nimrod: he began to be a mighty one in the earth."},
        "9": {"zh": "他在耶和华面前是个英勇的猎户，所以俗语说：像宁录在耶和华面前是个英勇的猎户。", "en": "He was a mighty hunter before Jehovah: wherefore it is said, Like Nimrod a mighty hunter before Jehovah."},
        "10": {"zh": "他国的起头是巴别、以力、亚甲、甲尼，都在示拿地。", "en": "And the beginning of his kingdom was Babel, and Erech, and Accad, and Calneh, in the land of Shinar."},
        "11": {"zh": "他从那地出来往亚述去，建造尼尼微、利河伯、迦拉，", "en": "Out of that land he went forth into Assyria, and builded Nineveh, and Rehoboth-Ir, and Calah,"},
        "12": {"zh": "和尼尼微、迦拉中间的利鲜，这就是那大城。", "en": "and Resen between Nineveh and Calah (the same is the great city)."},
        "13": {"zh": "麦西生路低人、亚拿米人、利哈比人、拿弗土希人、", "en": "And Mizraim begat Ludim, and Anamim, and Lehabim, and Naphtuhim,"},
        "14": {"zh": "帕斯鲁细人、迦斯路希人、迦斐托人；从迦斐托出来的有非利士人。", "en": "and Pathrusim, and Casluhim (whence went forth the Philistines), and Caphtorim."},
        "15": {"zh": "迦南生长子西顿，又生赫", "en": "And Canaan begat Sidon his first-born, and Heth,"},
        "16": {"zh": "和耶布斯人、亚摩利人、革迦撒人、", "en": "and the Jebusite, and the Amorite, and the Girgashite,"},
        "17": {"zh": "希未人、亚基人、西尼人、", "en": "and the Hivite, and the Arkite, and the Sinite,"},
        "18": {"zh": "亚瓦底人、洗玛利人、哈马人，后来迦南的诸族分散了。", "en": "and the Arvadite, and the Zemarite, and the Hamathite: and afterward were the families of the Canaanite spread abroad."},
        "19": {"zh": "迦南的境界是从西顿向基拉耳的路上，直到迦萨，又向所多玛、蛾摩拉、押玛、洗扁的路上，直到拉沙。", "en": "And the border of the Canaanite was from Sidon, as thou goest toward Gerar, unto Gaza; as thou goest toward Sodom and Gomorrah and Admah and Zeboiim, unto Lasha."},
        "20": {"zh": "这就是含的后裔，各随他们的宗族、方言，所住的地土、邦国。", "en": "These are the sons of Ham, after their families, after their tongues, in their lands, in their nations."},
        "21": {"zh": "雅弗的哥哥闪，是希伯子孙之祖，他也生了儿子。", "en": "And unto Shem, the father of all the children of Eber, the elder brother of Japheth, to him also were children born."},
        "22": {"zh": "闪的儿子是以拦、亚述、亚法撒、路德、亚兰。", "en": "The sons of Shem: Elam, and Asshur, and Arpachshad, and Lud, and Aram."},
        "23": {"zh": "亚兰的儿子是乌斯、户勒、基帖、玛施。", "en": "And the sons of Aram: Uz, and Hul, and Gether, and Mash."},
        "24": {"zh": "亚法撒生沙拉；沙拉生希伯。", "en": "And Arpachshad begat Shelah; and Shelah begat Eber."},
        "25": {"zh": "希伯生了两个儿子，一个名叫法勒，因为那时人就分地居住；法勒的兄弟名叫约坍。", "en": "And unto Eber were born two sons: the name of the one was Peleg; for in his days was the earth divided; and his brother's name was Joktan."},
        "26": {"zh": "约坍生亚摩答、沙列、哈萨玛非、耶拉、", "en": "And Joktan begat Almodad, and Sheleph, and Hazarmaveth, and Jerah,"},
        "27": {"zh": "哈多兰、乌萨、德拉、", "en": "and Hadoram, and Uzal, and Diklah,"},
        "28": {"zh": "俄巴路、亚比玛利、示巴、", "en": "and Obal, and Abimael, and Sheba,"},
        "29": {"zh": "阿斐、哈腓拉、约巴，这都是约坍的儿子。", "en": "and Ophir, and Havilah, and Jobab: all these were the sons of Joktan."},
        "30": {"zh": "他们所住的地方是从米沙直到西发东边的山。", "en": "And their dwelling was from Mesha, as thou goest toward Sephar, the mountain of the east."},
        "31": {"zh": "这就是闪的子孙，各随他们的宗族、方言，所住的地土、邦国。", "en": "These are the sons of Shem, after their families, after their tongues, in their lands, after their nations."},
        "32": {"zh": "这些都是挪亚三个儿子的宗族，各随他们的支派立国。洪水以后，他们在地上分为邦国。", "en": "These are the families of the sons of Noah, after their generations, in their nations: and of these were the nations divided in the earth after the flood."}
      }
    }
  }
};
